[package]
name = "rustygui"
version = "0.1.0"
authors = ["fwcd"]
build = "build.rs"

[dependencies]
log = "0.4"
simple_logger = "0.5.0"

[dependencies.sdl2]
version = "0.31"
features = ["ttf", "image", "mixer", "gfx"]
